// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV051J1GOhohdenxfsL8h5aLoKhZqm4Qs',
    appId: '1:83031781714:web:b6bb383c71f3fd9f2fca8b',
    messagingSenderId: '83031781714',
    projectId: 'fir-cloud-messaging-a637d',
    authDomain: 'fir-cloud-messaging-a637d.firebaseapp.com',
    storageBucket: 'fir-cloud-messaging-a637d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNc1iZjazcxVMbKdO6mZFSJ3Ekup6zZpU',
    appId: '1:83031781714:android:2c61a0272047d0222fca8b',
    messagingSenderId: '83031781714',
    projectId: 'fir-cloud-messaging-a637d',
    storageBucket: 'fir-cloud-messaging-a637d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd4vDCI__NGMa8OHO9jEYn2TGXP1EEOUI',
    appId: '1:83031781714:ios:11d1d1ac5b9a828c2fca8b',
    messagingSenderId: '83031781714',
    projectId: 'fir-cloud-messaging-a637d',
    storageBucket: 'fir-cloud-messaging-a637d.appspot.com',
    iosClientId: '83031781714-c74u313v4uvfn6sm188liaa295aod91v.apps.googleusercontent.com',
    iosBundleId: 'com.example.stateController',
  );
}
